spring:
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker

#spring:
#  config:
#    import: "optional:configserver:http://localhost:8088"
#  application:
#    name: discovery-service

